### ISSUE TITLE
Add PoS/TPoS last 1000 blocks rewards stats

### ISSUE THREAD

**Issue by xhiroz** [wiringbits/block-explorer#45]
From every block, get the reward amount, the utxo amount and the wait time (time that has passed since that utxo received the last reward).

Calculate and show averages.

**Comment by AlexITC** [comment]
The idea is to build something similar to what is shown [here](https://pivx.ccore.online/pos):
![pivx](https://user-images.githubusercontent.com/4218436/45503739-089e0400-b745-11e8-8b8f-a975d82c109d.png)

- Average POS input: The average of the amounts from the UTxOs that received the reward..
- Average wait time: For each reward on the last 1000 blocks, the average of the elapsed time since the UTxO received a reward.
- Average reward: The average reward amount on the last 1000 blocks.

**Comment by AlexITC** [comment]
Solved!

Thanks @iBlackShadow !!
